#ifndef __CHARACTERANIMATIONTYPE_H__
#define __CHARACTERANIMATIONTYPE_H__

enum CharacterAnimationType
{
	STAND_RIGHT,
	STAND_LEFT,
	MOVE_RIGHT,
	MOVE_LEFT,
	MELEE_RIGHT,
	MELEE_LEFT,
	PRIMARY_RIGHT,
	PRIMARY_LEFT,
	SECONDARY_RIGHT,
	SECONDARY_LEFT,
	GRENADE_RIGHT,
	GRENADE_LEFT,
	DIE_RIGHT,
	DIE_LEFT,
	DEAD_RIGHT,
	DEAD_LEFT,
	SPAWN_RIGHT,
	SPAWN_LEFT
};

#endif // __CHARACTERANIMATIONTYPE_H__